### ISSUE TITLE
dev-mq-infra-instance.yaml requires 'SyncOptions: Replace'

### ISSUE THREAD

**Issue by osowski** [cloud-native-toolkit/multi-tenancy-gitops#104]
Based on some of the CR fields that will change in the QueueManager's deployment YAML, not all of them are allowed to be changed on a running instance. For example, you cannot switch from a deployed SingleInstance Qmgr to a NativeHA Qmgr by updating/applying/patching the YAML.

By updating the ArgoCD Application to include the following options, it allows ArgoCD to replace the object outright and create it anew in the dev namespace:

```
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
```

We don't need this everywhere, but it allows for cleaner deployment in the dev-related pipelines with the ability to manually navigate some of the setup for the staging and prod namespaces that would have less likelihood to switch some of those forbidden properties.
