### ISSUE TITLE
Fix argocd app for CP4S Operator

### ISSUE THREAD

**Issue by hollisc** [cloud-native-toolkit/multi-tenancy-gitops#160]
Currently, there are 4 labels:

```
  labels:
    gitops.tier.group: ibm-cloudpak
    gitops.tier.layer: services
    gitops.tier.source: helm
    gitops.tier.source: git
```

The label `gitops.tier.source: git` needs to be removed
