### ISSUE TITLE
ArgoCD instance installed in a random namespace (NOT openshift-gitops)

### ISSUE THREAD

**Issue by giovanni-savino** [cloud-native-toolkit/multi-tenancy-gitops#282]
Dear team,

when deploying argocd instance, it does not have a namespace declared. ArgoCD is installed in a random namespace

eg
```
oc apply -f
../setup/ocp47/argocd-instance/argocd-instance.yaml
../setup/ocp4x/argocd-instance/argocd-instance.yaml
```

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops-cntk
spec:
```

Would it be better to declare it?

eg

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops-cntk
  namespace: openshift-gitops
spec:
```
