### ISSUE TITLE
dashboard icons route not working with ArgoCD

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/multi-tenancy-gitops#9]

**Comment by csantanapr** [comment]
cc @hollisc

**Comment by hollisc** [comment]
Deploying the `developer-dashboard` chart on OCP with ArgoCD without specifying a value for the `ingressSubdomain` or `host` parameters will cause the `dashboard-icons` route to fail the validation as the `host` parameter will default to `dashboard-icons.`.

Values.yaml: 
```
developer-dashboard:
  clusterType: "ocp4"
  ingressSubdomain: ""
  tlsSecretName: ""
  sso:
    enabled: true
  image:
    repository: "quay.io/ibmgaragecloud/developer-dashboard"
    tag: "v1.3.11"
  ingress:
    enabled: false
```
